//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceM9UF3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumne
    {
        public int id { get; set; }
        public string nom { get; set; }
        public Nullable<int> edat { get; set; }
    }
}
